server:
  port: 18300
  servlet:
    context-path: /nutritious-meal-user

spring:
  application:
    name: nutritious-meal-user
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.134.236:3306/nutritious_meal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Qian123#


nacos:
  config:
    server-addr: 120.78.134.236:8848
    bootstrap:
      enable: true
    remote-first: true
    data-ids: example
    group: DEFAULT_GROUP
    type: properties
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2333
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true
    username: nacos
    password: nacos
  discovery:
    server-addr: 120.78.134.236:8848
    auto-register: true
    register:
      ip: 1.1.1.1
      port: 1
      weight: 0.6D
      healthy: false
      enabled: true
      ephemeral: true
      group-name: nutritious-meal
    username: test